name: Resolve Sentry Issues
description: Resolves linked Sentry issues opened by Github
author: KYOS Energy Analytics

branding:
  color: 'green'
  icon: 'check'

inputs:
  token:
    description: Sentry Auth Token
    required: true
  org:
    description: Name of the Sentry Organization
    required: true

runs:
  using: node20
  main: dist/index.js
